---

- name: point enter

  hosts: host
  
  become: yes 
  become_user: root
  become_method: sudo

  tasks:

  - name: reload systemd
    shell: "systemctl daemon-reload"


#- import_playbook: file-system/hdd-mount.yml
#- import_playbook: file-system/create-directories.yml
#- import_playbook: ftp/ftp-settings.yml
- import_playbook: deluge/torrent-sheduler.yml
  